application: afishalvivparser
version: 6
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: "2.3"
- name: django
  version: "1.2"

handlers:
- url: .*
  script: main.app